# EC2 app host for PayWatch (Phase 3, Task 3).

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }
  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- SSH key pair (generated by Terraform - none existed in AWS or locally) --
resource "tls_private_key" "ec2_ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "ec2_ssh" {
  key_name   = "${var.project_name}-ec2-key"
  public_key = tls_private_key.ec2_ssh.public_key_openssh
}

resource "local_sensitive_file" "ec2_ssh_private_key" {
  filename        = "${path.module}/${var.project_name}-ec2-key.pem"
  content         = tls_private_key.ec2_ssh.private_key_pem
  file_permission = "0600"
}

# --- EC2 instance ------------------------------------------------------------

resource "aws_instance" "app" {
  ami                         = data.aws_ami.al2023.id
  instance_type               = "t3.small"
  subnet_id                   = aws_subnet.public_us_east_1a.id
  vpc_security_group_ids      = [aws_security_group.sg_ec2.id]
  iam_instance_profile        = aws_iam_instance_profile.ec2_instance_profile.name
  key_name                    = aws_key_pair.ec2_ssh.key_name
  associate_public_ip_address = true

  user_data = templatefile("${path.module}/templates/user_data.sh.tpl", {
    aws_region     = var.aws_region
    account_id     = data.aws_caller_identity.current.account_id
    github_repo    = var.github_repo
    redis_endpoint = aws_elasticache_replication_group.redis.primary_endpoint_address
  })
  # Ensures editing the script later (once Phase 4 lands) replaces the
  # instance so it actually re-runs - user_data only executes on first boot.
  user_data_replace_on_change = true

  tags = {
    Name = "${var.project_name}-ec2"
  }
}

# --- Elastic IP ----------------------------------------------------------

resource "aws_eip" "app" {
  instance = aws_instance.app.id
  domain   = "vpc"

  tags = {
    Name = "${var.project_name}-eip"
  }
}
